class UserAlreadyExistsError(Exception):
    pass

class UserNotFountError(Exception):
    pass